### ISSUE TITLE
Crash when saving

### ISSUE THREAD

**Issue by aholla** [natsuite/NatShare-API#104]
The first time I try and save a video using the native share panel, I am asked for permission and on granting it, my app crashes. This doesnt always happen...

**Comment by olokobayusuf** [comment]
Hey there @aholla, can you be more descriptive about the crash? What device and OS version are you running on. Can you share your sharing code, and the crash logs or any useful screenshots you have. I'd assume that you're on iOS, and you're getting the crash because your app doesn't specify the `NSPhotoLibraryUsageDescription` key in the `Info.plist`, along with requesting permission from the user to allow access to the camera roll.

**Comment by aholla** [comment]
HI this was a one off. Im not sure if I can replicate it so please close.
